### ISSUE TITLE
Refused to display widget on iFrame

### ISSUE THREAD

**Issue by brunocasarotti** [clicksign/widget#22]
Estou tentando inicializar o widget dentro de um iFrame executando em _localhost_ e o widget não abre. Olhando no console do Chrome o seguinte erro é retornado:

`Refused to display 'https://widget.clicksign-demo.com/?origin=http%3A%2F%2Flocalhost&email=xxxxxxxx&display_name=xxxxxxxxxx&documentationxxxx&birthday=xxxxxxxxx' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by mbbernstein** [comment]
@brunocasarotti Por favor, envie um e-mail para suporte@clicksign.com.
